name: docker-build-ubuntu-22.04-base

on: workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build -f dockerfiles/ubuntu-22.04-base -t ghcr.io/${{ github.actor }}/rocm_docker:ubuntu-22.04-base .
    - run: docker push ghcr.io/${{ github.actor }}/rocm_docker:ubuntu-22.04-base
    - run: docker image prune -a -f