name: docker-build-automatic

on: push

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build -f dockerfiles/automatic -t ghcr.io/${{ github.actor }}/rocm_docker:automatic .
    - run: docker push ghcr.io/${{ github.actor }}/rocm_docker:automatic