name: docker-build-a1111-webui

on: workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ghcr.io/r3dlobst3r/rocm_docker:ubuntu-22.04-base
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build -f dockerfiles/a1111-webui -t ghcr.io/${{ github.actor }}/rocm_docker:a1111-webui .
    - run: docker push ghcr.io/${{ github.actor }}/rocm_docker:a1111-webui