name: docker-build-automatic

on: workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build -f dockerfiles/automatic -t ghcr.io/${{ github.actor }}/rocm_docker:automatic .
    - run: docker push ghcr.io/${{ github.actor }}/rocm_docker:automatic
    - run: docker rmi $(docker images | egrep --ignore-case "/$IMAGEREGISTRYNAME\s" | egrep --invert-match "latest|$TAGVERSION" | tr --squeeze-repeats ' ' | cut --delimiter ' ' --fields 3)